// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XHLS_HOTSPOT_H
#define XHLS_HOTSPOT_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xhls_hotspot_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XHls_hotspot_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XHls_hotspot;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XHls_hotspot_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XHls_hotspot_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XHls_hotspot_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XHls_hotspot_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XHls_hotspot_Initialize(XHls_hotspot *InstancePtr, u16 DeviceId);
XHls_hotspot_Config* XHls_hotspot_LookupConfig(u16 DeviceId);
int XHls_hotspot_CfgInitialize(XHls_hotspot *InstancePtr, XHls_hotspot_Config *ConfigPtr);
#else
int XHls_hotspot_Initialize(XHls_hotspot *InstancePtr, const char* InstanceName);
int XHls_hotspot_Release(XHls_hotspot *InstancePtr);
#endif

void XHls_hotspot_Start(XHls_hotspot *InstancePtr);
u32 XHls_hotspot_IsDone(XHls_hotspot *InstancePtr);
u32 XHls_hotspot_IsIdle(XHls_hotspot *InstancePtr);
u32 XHls_hotspot_IsReady(XHls_hotspot *InstancePtr);
void XHls_hotspot_EnableAutoRestart(XHls_hotspot *InstancePtr);
void XHls_hotspot_DisableAutoRestart(XHls_hotspot *InstancePtr);


void XHls_hotspot_InterruptGlobalEnable(XHls_hotspot *InstancePtr);
void XHls_hotspot_InterruptGlobalDisable(XHls_hotspot *InstancePtr);
void XHls_hotspot_InterruptEnable(XHls_hotspot *InstancePtr, u32 Mask);
void XHls_hotspot_InterruptDisable(XHls_hotspot *InstancePtr, u32 Mask);
void XHls_hotspot_InterruptClear(XHls_hotspot *InstancePtr, u32 Mask);
u32 XHls_hotspot_InterruptGetEnabled(XHls_hotspot *InstancePtr);
u32 XHls_hotspot_InterruptGetStatus(XHls_hotspot *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
