// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xhls_hotspot.h"

extern XHls_hotspot_Config XHls_hotspot_ConfigTable[];

XHls_hotspot_Config *XHls_hotspot_LookupConfig(u16 DeviceId) {
	XHls_hotspot_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XHLS_HOTSPOT_NUM_INSTANCES; Index++) {
		if (XHls_hotspot_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XHls_hotspot_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XHls_hotspot_Initialize(XHls_hotspot *InstancePtr, u16 DeviceId) {
	XHls_hotspot_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XHls_hotspot_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XHls_hotspot_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

